# Generated by Django 4.2.3 on 2023-07-24 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_initial'),
        ('school', '0002_classroomlist_levelchoice_subjectlist_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelchoice',
            name='is_high_school',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='SchoolYearTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolyear')),
                ('subject_taught', models.ManyToManyField(to='school.subjectlist')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYearStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_promotion', models.BooleanField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student')),
            ],
        ),
        migrations.CreateModel(
            name='MarkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_mark', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelmarks', to='school.level')),
            ],
            options={
                'unique_together': {('level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('mark2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('mark_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marktypemarks', to='school.marktype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentmarks', to='school.schoolyearstudent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectmarks', to='school.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatedmarks', to='people.teacher')),
            ],
            options={
                'ordering': ['student'],
                'unique_together': {('student', 'subject', 'mark_type')},
            },
        ),
    ]
