# Generated by Django 4.2.3 on 2023-07-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_levelchoice_is_high_school_schoolyearteacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachersubjects', to='school.schoolyearteacher'),
        ),
    ]
