# Generated by Django 4.2.3 on 2023-07-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolyearteacher',
            name='classroom',
        ),
    ]
