# Generated by Django 4.2.3 on 2023-07-30 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0005_remove_schoolyearteacher_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="le nom peut etre mensuel, trimestriel ou semestriel. Ex: ('Janvier', '1er trimestre')", max_length=200)),
                ('is_current', models.BooleanField(help_text="en l'activant, il devient l'emploi du temps courant que les professeurs et élèves vérons dans leur interface")),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolyear')),
            ],
            options={
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.AlterField(
            model_name='schoolyearstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentsystudents', to='people.student'),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercrédi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], max_length=50)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroomtimetables', to='school.classroom')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.monthlyschedule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjecttimetables', to='school.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="titre de l'information", max_length=100)),
                ('content', models.TextField(help_text="contenu de l'information")),
                ('to_all', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classroom')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.level')),
            ],
        ),
    ]
