# Generated by Django 4.2.3 on 2023-08-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_monthlyschedule_alter_schoolyearstudent_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinfo',
            name='is_active',
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='to_classroom',
        ),
        migrations.RemoveField(
            model_name='schoolinfo',
            name='to_level',
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='to_classroom',
            field=models.ManyToManyField(to='school.classroom'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='to_level',
            field=models.ManyToManyField(to='school.level'),
        ),
    ]
