# Generated by Django 4.2.3 on 2023-08-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_schoolinfo_is_active_schoolinfo_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='school_year',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='schoolyearinfos', to='school.schoolyear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='to_classroom',
            field=models.ManyToManyField(related_name='classroominfos', to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='to_level',
            field=models.ManyToManyField(related_name='levelinfos', to='school.level'),
        ),
    ]
