# Generated by Django 4.2.3 on 2023-07-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(1, 'masculin'), (0, 'féminin')], default=1, null=True)),
                ('age', models.IntegerField(default=10, null=True)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(1, 'masculin'), (0, 'féminin')], default=1, null=True)),
                ('age', models.IntegerField(default=10, null=True)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(1, 'masculin'), (0, 'féminin')], default=1, null=True)),
                ('age', models.IntegerField(default=10, null=True)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(1, 'masculin'), (0, 'féminin')], default=1, null=True)),
                ('age', models.IntegerField(default=10, null=True)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
