# Generated by Django 4.2.3 on 2023-09-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_timetable_classroom_alter_timetable_subject_and_more'),
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='school.subjectlist'),
        ),
    ]
